kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admins-binding-internal
  namespace: "test1"
subjects:
- kind: Group
  name: k8s-namespace-administrators-k8s-test1-internal
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io