apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  namespace: test1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - image: harbor.idp-poc.tremolo.dev/test1/mypython:XXXXXX
        imagePullPolicy: Always
        name: test1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: pull-secret
      dnsPolicy: ClusterFirst
      imagePullSecret: pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30